filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        code_rating: true
        duplication: true
        parameter_doc_comments: true

tools:
    external_code_coverage: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    
